### ISSUE TITLE
adding other Victron devices

### ISSUE THREAD

**Issue by schonstudent** [hoberman/Victron_BLE_Advertising_example#5]
Hi Hoberman,
is there a plan to add a second device like a "Victron Orion" or maybe did you do it already?
Best
Sascha

**Comment by hoberman** [comment]
The only Victron products I own or have access to are the SmartSolar charge controllers, so I'm unable to provide code for other devices. My intent with this code is to provide a (reasonably) simple example of how to receive, decrypt, and decode Victron data broadcasts. I'm hoping that people can use this code as a starting point and adapt it to work with other Victron hardware. Good luck!
