### ISSUE TITLE
Manufacturing Data Zero Byte

### ISSUE THREAD

**Issue by surfermarty** [hoberman/Victron_BLE_Advertising_example#6]
Using this to decode a different Victron device - a Battery Protect. Older expressif worked fine; using the newer libraries (String) and it stopped working. Traced it to the line manData.toCharArray((char *)manCharBuf,manDataSize+1);

String.toCharArray seems to respect zero byte terminators, and in my case byte 4 of the Victron mfg data was zero - so only 3 bytes get copied.

Replaced with 

memcpy(manCharBuf,manData.c_str(),manDataSize);

and now I'm getting full mfg data on a battery protect under the new library.

Hopefully this might help someone.

**Comment by hoberman** [comment]
You are correct: zero-valued bytes will cause the manufacturer data to get truncated because of the inner workings of String toCharArray() - and getBytes() too! I've adjusted my code with your suggested fix and added comments trying to explain the situation. Thanks!
